title: Atta Ul Haleem
description: A personal portfolio website.
theme: just-the-docs

url: https://Attaulhaleem.github.io

aux_links:
  Template Repository: https://github.com/Attaulhaleem/Attaulhaleem.github.io
